import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={[inter.className, 'bg-gradient-to-bl from-[#380036] to-[#044141]', 'text-gray-50','min-h-screen'].join(' ')}>
        <header className='mx-auto flex flex-row justify-between min-w-screen px-3 py-6 sticky top-0 z-50 bg-[#360835]'>
            <div className='logo-section'>
              <span className='bg-gradient-to-br from-red-500 to-yellow-100 bg-clip-text text-xl font-bold text-transparent'>Sreejit's blog</span>
            </div>
            <ul className='flex flex-row gap-5'>
              <li>Blogs</li>
              <li>Github</li>
              <li>Twitter</li>
            </ul>
        </header>
        {children}
      </body>
    </html>
  )
}
